### ISSUE TITLE
ModuleNotFoundError: No module named 'fastai2'

### ISSUE THREAD

**Issue by araragi-koyomi-sama** [fastai/fastbook#190]
when i try to run the code in the first module, i get this error, i have already installed fastai but when i try to install fastai2 whit pip i get ERROR: No matching distribution found for torch>=1.3.0 (from fastai2)

**Comment by LopezGG** [comment]
I ran the following inside one of the cells to get started

```
import sys
!{sys.executable}- m pip install -r requirements.txt
```

**Comment by AH-Merii** [comment]
You need install the requirements that are in the requirements.txt file.

The best way to do that is by creating a new virtual environment; I personally use miniconda3.

In order to do that you first need to install miniconda3, then you need to run the following command in the terminal:

`conda create --name env_name --file requirements.txt python=3.8.5`

Make sure that you are in the same directory as the requirements.txt file, when running the command above. 

Finally make sure to select this new environment in your notebook.
