### ISSUE TITLE
Download more than 150 images using the Bing Image Search API

### ISSUE THREAD

**Issue by oddrationale** [fastai/fastbook#244]
Currently, the `utils.py` only allows a maximum of 150 images. This is because the [Bing Image Search API](https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-images-api-v7-reference#query-parameters) only allows 150 images to be return per request.

However, the `offset` query parameter should allow us to page through and return more than 150 images.

It would be nice to update the `search_images_bing()` function in `utils.py` to allow more than 150 images to be downloaded.

**Comment by oddrationale** [comment]
PR #243

**Comment by oddrationale** [comment]
Forum discussion post:
https://forums.fast.ai/t/getting-more-than-150-images-using-search-images-bing/77947/2

**Comment by prairie-guy** [comment]
Would it make sense to incude this extended version of `search_images_bing()` within fastai/fastai/vision/utils.py? I really like the functionality provided by this PR. I understand that it doesn’t make sense to include within fastai/fastbook/utils.py. I think finding images for training vision models would be an appropriate addition to fastai itself, as it is core to the process of creating vision models. I also created a function `search_images_dgd` and a PR https://github.com/fastai/fastbook/pull/250 which could be considered to be included there as well.

In terms of proper etiquette, I apologize in advance if I should be discussing this on the fourm instead of here. I will make a post to the forums as well. This is my third time through the course and I am finally in a position where I can make suggestions and want to do so constructively. Thanks.

**Comment by oddrationale** [comment]
Closing issue as PR was not accepted and code snippet can be found on the forums.
