### ISSUE TITLE
Should variables ever be shortened?

### ISSUE THREAD

**Issue by Anahkiasen** [fastai/fastbook#409]
Since those are educational notebooks, and they're for the most part very lengthy, should variables ever ever be shortened? 🤔 I'm talking about `ds` for `Dataset`, `dl` for `DataLoader`, `opt` for the optimizer, and even simpler ones like `w` for weights and so on. 

As there's often quite a bit of text in between code cells I constantly have to go back and forth to check what was a given variable and it's slowing me down dramatically (because the performance tends to tank when scrolling large notebooks), and I don't feel it's really improving the legibility all that much. 😕  I don't fully see the benefit in variables being shortened in relatively static code, since the main benefit of shortened variables to me is typing speed.

I'd prefer if everything was spelt out (besides `X` and `y` which are a different story 😛 ), I feel it would also give people better good practices in terms of naming since there's a shitload of notebooks out there with terrible naming scheme since they were made by people without a programming background, so I feel it's important to give the right example. 
This is also true for functions and such, I'd much rather prefer `calc_grad` to be `calculate_gradient`, I don't feel the few extra characters impede on the code if anything I think it makes it much clearer and avoids having to do back and forth constantly.

I'd be willing to make a PR but I'd prefer the approval of the maintainers first since this could take some time even with automatic renaming.

**Comment by aberres** [comment]
I doubt Jeremy is willing to change this as he explicitly explains why he uses this style.

But I am on your side. Especially the function naming is often more confusing than helpful. It might be that one gets used to it, but when not being to deep into the code base I find it pretty obfuscating.
Reminds me of a legacy C++ code base I used to work with ;-)

Personally I try to use complete words and even format my notebooks with [nb_black](https://github.com/dnanhkhoa/nb_black)

**Comment by Anahkiasen** [comment]
That's unfortunate, I hope if enough people voice their support in this issue the authors would be willing to change this. I'm currently testing my knowledge on AIQuizzes, and the very fact questions like this needs the precision is very telling to me that something could be improved. :/ 

![Screenshot 2021-02-19 at 15 02 53](https://user-images.githubusercontent.com/1321596/108514040-a5284100-72c3-11eb-9fdd-90ac80b58d8d.png)

**Comment by zxul767** [comment]
I agree with you @Anahkiasen, in particular when it comes to names in the public API. For example: `bs` is just not an intuitive name for `batch_size` in a public API, and I don't think the benefit of typing fewer characters is enough to justify the loss of readability and the additional burden this puts on students.

Even the "but we have to type more" argument seems weak to me since one can always write in "short mode" and "find and replace" before committing changes. Code is read more often than it is written, so picking more readable names matters.

Of course, one has to be careful to choose good names that strike a balance between readability and conciseness. It's easy to get carried away as it has happened in other languages that use overly verbose names (e.g., Objective-C).

>  There are only two hard things in Computer Science: cache invalidation and naming things. -- Phil Karlton

**Comment by Rebolforces** [comment]
@jph00 can be closed. Debate on naming-styles, (better as a discussion on https://forums.fast.ai/)
