### ISSUE TITLE
04_minst_basics 'An End-to-End SGD Example/Step 6' - subplots do not converge when GPU enabled

### ISSUE THREAD

**Issue by pjgoodall** [fastai/fastbook#454]
**If I load `04_mnist_basics.ipynb` into Google Colab, the sub-plots for  'An End-to-End SGD Example/Step 6' look like this in the saved outputs:**

![image](https://user-images.githubusercontent.com/719962/121646434-ac749400-cad8-11eb-82a3-0272c89bc6b5.png)

**If I run up-to and including the same cell with the GPU disabled:**

![image](https://user-images.githubusercontent.com/719962/121646852-168d3900-cad9-11eb-8983-b4697c4f3897.png)

**Enable the GPU and reset, run from the beginning:**

![image](https://user-images.githubusercontent.com/719962/121646569-ce6e1680-cad8-11eb-9ef1-eb26ed69c8fa.png)

**Comment by pjgoodall** [comment]
Is there some reason this never gets looked at? If I've made some basic error please let me know. I tried this again yesterday, and the example fails to converge with or without GPU. Posted on forums.fast.ai
Crickets are deafening...

**Comment by amritpurshotam** [comment]
I encountered the same issue and proposed a fix in #450. The reason for the difference between the saved outputs and what actually happens is that the `mse()` function was changed from
```python
def mse(preds, targets): return ((preds-targets)**2).mean()
```
to
```python
def mse(preds, targets): return ((preds-targets)**2).mean().sqrt()
```
without the cells being re-run (see my PR for more details). As you can see the Mean Square Error (MSE) function was erroneously changed to the Root Mean Square Error (RMSE) which leads to a much smaller loss and consequently a much smaller gradient update (this is why the graph looks the same since the update is so small it's not visibly noticeable). So to get the graphs shown in the saved outputs, update the cell containing the `mse()` function and remove the `.sqrt()`.

**Comment by pjgoodall** [comment]
@amritpurshotam 
Thank-you very much! That explains it. These are introductory examples. I am very disappointed that I have posted on three different environments about this and no-one noticed before you. 
I'm a beginner at this so don't yet have the tools to troubleshoot what was supposed to be a simple introductory problem.
Cheers...

**Comment by tmabraham** [comment]
@jph00 can be closed
