### ISSUE TITLE
learn.export() and learn_inf = load_learner('export.pkl') not working

### ISSUE THREAD

**Issue by saprativa** [fastai/fastbook#472]
I tried to export the cats vs dogs model of Notebook 1 with 

```learn.export() ```

and then loaded using 

```learn_inf = load_learner('export.pkl')```

but got the following error:

```AttributeError: Can't get attribute 'is_cat' on <module '__main__'>```

on google colab. I am talking about:

```
path = untar_data(URLs.PETS)/'images'

def is_cat(x): return x[0].isupper()
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))

learn = cnn_learner(dls, resnet34, metrics=error_rate, path=".")
learn.fine_tune(1)
```

Am I missing something here?

**Comment by zxul767** [comment]
I ran the code in [this notebook](https://colab.research.google.com/github/fastai/fastbook/blob/master/01_intro.ipynb) and didn't get an exception. However, I do remember having run into perhaps the same error some time ago, and eventually found that the problem was explained in the [documentation](
https://docs.fast.ai/learner.html#Learner.export):

> The Learner is saved in `self.path/fname`, using pickle_protocol. Note that serialization in Python saves the names of functions, not the code itself. Therefore, any custom code you have for models, data transformation, loss function etc., should be put in a module that you will import in your training environment before exporting, and in your deployment environment before loading it.

Apparently, this happens only when you're loading the model in a new session where the `is_cat` function is not yet loaded:

![7BE90D9E-1996-4766-9CC1-2F26B9BB84F1](https://user-images.githubusercontent.com/442314/135200293-04625e1f-765e-4725-a432-6f79eaad2cb2.png)

The reason why it works when the function is saved in another file is that the model is then saved with information about where the `is_cat` function came from (i.e., the file where it is stored), so it is possible to reload it just fine.

**Comment by saprativa** [comment]
Yeah so I need to have the ```is_cat``` definition in the new session where I am loading the model. Thanks. This resolves the issue.
